Repository TechpreneurCambodia/smean-frontend, pull requests merged in 2025-03, with the labels that each got.

#25 Close #24 authentication handle protected and public routes
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.js
  src/app/login/page.js
  src/app/signup/page.js
  src/components/Alert.js
  src/components/Layout.js
  src/components/ProtectedRoute.js
  src/components/PublicRoute.js
  src/services/api/auth.js
  src/services/axiosInstance.js
  src/services/utils/cookies.js
  src/services/utils/humanize.js
Labels: integrations, core

#42 Close #30 Recording Audio Integration
  package-lock.json
  src/app/RecordPage.js
  src/app/recordingpage/page.js
  src/components/TimeAndRecorder.js
  src/services/api/audios/uploadAudio.js
Labels: integrations

#76 Close #72 Welcome User Screen Fix
  src/app/home/Welcome.js
  src/app/home/page.js
  src/app/layout.js
  src/app/page.js
  src/contexts/userContext.js
Labels: integrations

#94 Close #89 Incorrect Note Labeling
  public/recording-transcription.svg
  public/voice-record.svg
  src/app/RecordPage.js
  src/app/recording/page.js
  src/app/upload/page.js
  src/components/Button.js
  src/components/MinuteOption.js
  src/components/TimeAndRecorder.js
  src/services/api/audios/uploadAudio.js
Labels: enhancement, integrations

#99 Close #80 Add Summary Interval Popup Component to Upload Page
  src/app/upload/page.js
  src/components/MinuteOption.js
  src/components/Steps.js
  src/components/UploadBox.js
  src/services/api/audios/uploadAudio.js
Labels: enhancement
